### ISSUE TITLE
Not working... Any tips?

### ISSUE THREAD

**Issue by benjivo** [arneson/gif-screensaver#2]
Url directory works fine, used provided gif URL as to ensure proper link format, preview shows black screen and did not seem to work.

Any help is appreciated. Thanks.

**Comment by iwantmac-hacks** [comment]
Update - in using a different gif URL, got it to show up in the preview
Alas, shows as a black screen in screensaver and background mode flips back to stop every time I set it to start.

**Comment by benjivo** [comment]
Update - screensaver works, background doesn't.
Keeps switching to stop every time I set it to start.

**Comment by arneson** [comment]
@iwantmac-hacks 
Oh right, I actually haven't tested that feature at all. What is it supposed to do?

**Comment by arneson** [comment]
Alright, I looked into it. So in the original repo this is stated:
Note: AnimatedGif is not working with Catalina(10.15) since screensavers are now sandboxed (this means no GIF files can be selected or read from local disk and also background mode is broken), see issue #57.

I've only resolved the gif file issue, not the background mode one. 

I'll close this ticket and create a new one for that issue specifically.( #3 )
